# This is a basic workflow to help you get started with Actions

name: CI-CD-sbondar
env:
  SB-bucket       : "sbondar05-github-actions"
  SB-app          : "sbondar05"
  SB-env          : "Sbondar05-env"
  SB-deploy       : "SB-app_${{ github.sha }}.zip"
  SB-AWS-region   : "eu-north-1"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci-part:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: git repo
        uses: actions/checkout@v2

      - name: create ZIP
        run: zip -r ${{ env.SB-deploy }} ./ -x *.git*
        
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id : ${{ secrets.SB_AWS_ACCESS_KEY }}
          aws-secret-key-id : ${{ secrets.SB_AWS_SECRET_KEY }}
          aws-region        : ${{ env.SB-AWS-region }}
          
      - name: copy deployment to S3
        run: aws s3 cp ${{ env.SB-deploy }} s3:// ${{ env.SB-bucket }}/

      # Runs a set of commands using the runners shell
      - name: message
        run:
          echo "CI part finished"
          #echo test, and deploy your project.
