# This is a basic workflow to help you get started with Actions

name: CI-CD-sbondar
env:
  SB-bucket       : "sbondar05-github-actions"
  SB-app          : "sbondar05"
  SB-env          : "Sbondar05-env"
  SB-deploy       : "SB-app_${{ github.sha }}.zip"
  SB-AWS-region   : "eu-north-1"
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci-part:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: git repo
        uses: actions/checkout@v2

      - name: create ZIP
        run: zip -r ${{ env.SB-deploy }} ./ -x *.git*

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
       # run: zip -r ${{ env.SB-deploy }} ./ -x *.git*
         # echo Add other actions to build,
          #echo test, and deploy your project.
